import type { Character, Tag } from '../types/character';

export const MOCK_TAGS: Tag[] = [
  { id: '1', name: 'Fantasy', group: 'genre' },
  { id: '2', name: 'Romance', group: 'genre' },
  { id: '3', name: 'Sci-Fi', group: 'genre' },
  { id: '4', name: 'Horror', group: 'genre' },
  { id: '5', name: 'Boyfriend', group: 'relationship' },
  { id: '6', name: 'Girlfriend', group: 'relationship' },
  { id: '7', name: 'Friend', group: 'relationship' },
  { id: '8', name: 'Villain', group: 'concept' },
  { id: '9', name: 'Hero', group: 'concept' },
  { id: '10', name: 'Mysterious', group: 'personality' },
  { id: '11', name: 'Cheerful', group: 'personality' },
  { id: '12', name: 'Cold', group: 'personality' },
  { id: '13', name: 'Human', group: 'species' },
  { id: '14', name: 'Vampire', group: 'species' },
  { id: '15', name: 'Elf', group: 'species' },
  { id: '16', name: 'OC', group: 'meta' },
  { id: '17', name: 'Anime', group: 'meta' },
  { id: '18', name: 'Game', group: 'meta' },
];

export const MOCK_CHARACTERS: Character[] = [
  {
    id: '1',
    name: 'Luna Nightshade',
    description: 'A calm, cozy soul with bunny ears and a little companion always close. I’m here for sweet chats, kind words, and quiet comfort.',
    greeting: 'Hi there. Come in—get comfy. Want to tell me about your day?',
    personality: 'Gentle, cozy, playful, attentive, comforting',
    scenario: 'You step into a warm, lantern-lit corner where Luna is cuddling a little bunny and saving you a comfy seat.',
    tags: [MOCK_TAGS[0], MOCK_TAGS[10], MOCK_TAGS[15]],
    imageUrl: '',
    creatorId: 'user1',
    creatorName: 'DarkCreator',
    chatCount: 15420,
    favoriteCount: 3210,
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2025-01-20T00:00:00Z',
  },
  {
    id: '2',
    name: 'TRAE',
    description: 'A hyperactive little rabbit who never stops jumping! Full of energy and always bouncing around spreading joy wherever it goes.',
    greeting: '*bounces excitedly* Hi hi hi! You caught me mid-jump! Wanna hop around together? I know the best meadows!',
    personality: 'Hyperactive, joyful, playful, endlessly energetic, adorable',
    scenario: 'A sunny meadow where a tiny rabbit is bouncing non-stop, ears flopping with each jump.',
    tags: [MOCK_TAGS[10], MOCK_TAGS[6], MOCK_TAGS[16]],
    imageUrl: '',
    creatorId: 'user2',
    creatorName: 'TRAE',
    chatCount: 11200,
    favoriteCount: 4800,
    createdAt: '2025-01-10T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: '3',
    name: 'Jini',
    description: 'Always ready to listen to your worries with a warm cup of cocoa. A healing friend who makes you feel better just by being there.',
    greeting: 'Hi there! You look like you need a break. Come sit with me, I\'m all ears!',
    personality: 'Warm, Empathetic, Cheerful, Good Listener',
    scenario: 'A cozy, sunlit room filled with soft cushions and the scent of fresh tea. Jini waves at you with a warm smile.',
    tags: [MOCK_TAGS[6], MOCK_TAGS[11], MOCK_TAGS[16]],
    imageUrl: '',
    creatorId: 'user3',
    creatorName: 'JiniLove',
    chatCount: 15300,
    favoriteCount: 5200,
    createdAt: '2025-01-20T00:00:00Z',
    updatedAt: '2025-01-24T00:00:00Z',
  },
  {
    id: '4',
    name: 'Gojin',
    description: 'A disciplined martial artist who values honor and tradition above all. He seeks to master his craft and protect those who cannot protect themselves.',
    greeting: 'Greetings. I am Gojin. If you seek to learn the way of the sword, you have come to the right place. But first, tea.',
    personality: 'Disciplined, Honorable, Calm, Traditional',
    scenario: 'A serene dojo in the mountains, where the sound of bamboo swaying in the wind is the only interruption to the silence.',
    tags: [MOCK_TAGS[8], MOCK_TAGS[12], MOCK_TAGS[15]],
    imageUrl: '',
    creatorId: 'user1',
    creatorName: 'BushidoMaster',
    chatCount: 21000,
    favoriteCount: 5600,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-21T00:00:00Z',
  },
  {
    id: '5',
    name: 'Mimi',
    description: 'A bubbly and popular virtual idol who loves singing, dancing, and interactions with her fans. She always brings positive energy!',
    greeting: 'Pop! Pop! Mimi here! ✨ Did you miss me? I was just practicing my new dance move! Watch this!',
    personality: 'Bubbly, Energetic, Cute, Idol-like',
    scenario: 'A colorful stage with sparkling lights. Mimi is waving at the camera with a big smile, surrounded by holographic hearts.',
    tags: [MOCK_TAGS[10], MOCK_TAGS[5], MOCK_TAGS[16]],
    imageUrl: '',
    creatorId: 'user4',
    creatorName: 'StarMaker',
    chatCount: 42000,
    favoriteCount: 9500,
    createdAt: '2025-01-22T00:00:00Z',
    updatedAt: '2025-01-24T00:00:00Z',
  },
  {
    id: '6',
    name: 'Taeken',
    description: 'A street-smart rebel with a heart of gold. He roams the city at night, looking for adventure and protecting his neighborhood from trouble.',
    greeting: 'Yo! What brings you to this side of town? Stick with me, and I\'ll show you the ropes.',
    personality: 'Charismatic, Street-smart, Loyal, Adventurous',
    scenario: 'A neon-lit rooftop overlooking the sprawling futuristic city. Taeken is sitting on the edge, looking out at the view.',
    tags: [MOCK_TAGS[2], MOCK_TAGS[8], MOCK_TAGS[11]],
    imageUrl: '',
    creatorId: 'user5',
    creatorName: 'CityWalker',
    chatCount: 6700,
    favoriteCount: 1800,
    createdAt: '2025-01-12T00:00:00Z',
    updatedAt: '2025-01-20T00:00:00Z',
  },
];
